
import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "./MainLayout.tsx/Navbar";
import Footer from "./MainLayout.tsx/Footer";
import { Toaster } from "@/components/ui/sonner";
import LenisProvider from "./LenisProvider";

// Load Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "CyberChetana",
  description: "Generated by Hacfy",
  icons: { icon: "/HC.png" },
  keywords: [],
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // useLenis();
  return (
    <html lang="en">
      {/* Apply Poppins font */}
      <body className={`${poppins.variable} font-poppins antialiased`}>
        <LenisProvider>
          <Navbar />
          <main>{children}</main>
          <Toaster />
          <Footer />
        </LenisProvider>
      </body>
    </html>
  );
}
